[providers]

[providers.kubernetes]
 source  = "hashicorp/kubernetes"
 versions = ["2.16.1", "2.16.0", "2.17.0"]
 platforms = [
  {os = "linux", arch =  "amd64"},
  {os = "darwin", arch =  "arm64"},
 ]


[client]
 timeout = 30
 workDir = "/tmp/tfmirror"

[providers.random]
source  = "hashicorp/random"
#versions = ["2.2.1"]
arch = ["amd64"]
os = ["linux"]
